#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config active_border_color '#C5A5BC'
bspc config normal_border_color '#C5A5BC'
bspc config focused_border_color '#C5A5BC'
bspc config border_radius        7
bspc config gapless_monocle false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wal -r
polybar
picom --experimental-backends -b

bspc rule -a cool-retro-term state=floating center=true rectangle    =1300x700+0+0
cool-retro-term -e sh -c "ez.sh && sleep 2"
bspc rule -r cool-retro-term
$SHELL
